version: 0.2

phases:
  pre_build:
    commands:
      echo pull loadimpact/k6 image..
      docker pull loadimpact/k6
  build:
    commands:
      echo run performance test
      docker run -i loadimpact/k6 run - <k6-aws/scripts/k6_AWS.js
  post_build:
    commands:
      echo Performance test complete